### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by itsff** [MartinF/Dynamo.IoC#5]
I couldn't find a license file anywhere...

**Comment by MartinF** [comment]
Hello Filip, 

To be honest haven't really thought about it.
As long as people don’t copy my work and call it their own I am just glad people can find some use of it.

I would like to be credited for the work, and it is of course funny to know where it is being used.

Other than that it is absolutely free for anyone to use.

Best regards

Martin

-----Oprindelig meddelelse-----
Fra: Filip Frącz [mailto:reply@reply.github.com] 
Sendt: 19. juli 2012 20:20
Til: Martin From
Emne: [DynamoIOC] What's the license? (#5)

I couldn't find a license file anywhere...

---

Reply to this email directly or view it on GitHub:
https://github.com/MartinF/DynamoIOC/issues/5

**Comment by itsff** [comment]
Martin,

Thanks for the response. Cost is one thing, but liability is the other :-) Gotta keep those lawyers happy. Some projects won't use code licensed under strong copy-left license that force publishing own sources (ex. GPL).
Maybe you should consider [New BSD](http://en.wikipedia.org/wiki/BSD_licenses) or [MIT](http://en.wikipedia.org/wiki/MIT_License) license. I'm not a lawyer, but they state you're not liable for problems that may raise from using your software.

**Comment by MartinF** [comment]
Thanks. Maybe New BSD is the right one for this project. I am not a lawyer either - obviously :)
