### ISSUE TITLE
Nuget packages

### ISSUE THREAD

**Issue by devatwork** [MartinF/Dynamo.IoC#6]
Hello Martin,

When do you expect to release the new version of Dynamo IoC on NuGet?

If you want I can submit a pull- request for the package descriptor and a small build process.

Let met know..

Regards,
Bert

**Comment by MartinF** [comment]
Hello Bert,

i have just updated Nuget with the new version (now split into Dynamo.Ioc, Dynamo.Ioc.Extensions and Dynamo.Ioc.Web).

Best regards

Martin
